"""add delivery log audit table

Revision ID: 194a00b0adab
Revises: 3587f7ab9d59
Create Date: 2026-02-12 03:14:34.471986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194a00b0adab'
down_revision: Union[str, Sequence[str], None] = '3587f7ab9d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), server_default='telegram', nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('send_status', sa.String(), nullable=False),
    sa.Column('consume_status', sa.String(), server_default='NOT_ATTEMPTED', nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_log_run_id'), 'delivery_log', ['run_id'], unique=False)
    op.create_index('ix_delivery_log_user_created', 'delivery_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_delivery_log_user_id'), 'delivery_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_log_user_id'), table_name='delivery_log')
    op.drop_index('ix_delivery_log_user_created', table_name='delivery_log')
    op.drop_index(op.f('ix_delivery_log_run_id'), table_name='delivery_log')
    op.drop_table('delivery_log')
    # ### end Alembic commands ###
