"""subscription plan + stripe ids

Revision ID: 3d6f1f4f2598
Revises: fbd8788d9bee
Create Date: 2026-02-11 16:31:54.983800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6f1f4f2598'
down_revision: Union[str, Sequence[str], None] = 'fbd8788d9bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
