"""add usage_count

Revision ID: 596ecd464a82
Revises: 3d6f1f4f2598
Create Date: 2026-02-11 18:39:15.516811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596ecd464a82'
down_revision: Union[str, Sequence[str], None] = '3d6f1f4f2598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'usage_count')
    # ### end Alembic commands ###
