"""add gold intelligence tables

Revision ID: 82f588700b16
Revises: fcef483cb7b9
Create Date: 2026-02-12 00:03:28.543128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f588700b16'
down_revision: Union[str, Sequence[str], None] = 'fcef483cb7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_positioning_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('as_of_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cot_net_non_commercial', sa.Integer(), nullable=True),
    sa.Column('comex_open_interest', sa.Integer(), nullable=True),
    sa.Column('gld_flow_tonnes', sa.Float(), nullable=True),
    sa.Column('iau_flow_tonnes', sa.Float(), nullable=True),
    sa.Column('crowding_score', sa.Float(), nullable=False),
    sa.Column('positioning_bias', sa.String(), nullable=False),
    sa.Column('squeeze_risk', sa.String(), nullable=False),
    sa.Column('contra_signal', sa.Boolean(), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_positioning_snapshot_as_of_utc'), 'gold_positioning_snapshot', ['as_of_utc'], unique=False)
    op.create_table('gold_regime_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('as_of_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('allowed_direction', sa.String(), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_regime_daily_as_of_utc'), 'gold_regime_daily', ['as_of_utc'], unique=False)
    op.create_table('gold_stress_intraday',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('as_of_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('basis_bps', sa.Float(), nullable=True),
    sa.Column('front_month_spread_bps', sa.Float(), nullable=True),
    sa.Column('spread_volatility_bps', sa.Float(), nullable=True),
    sa.Column('inventory_stress_score', sa.Float(), nullable=True),
    sa.Column('stress_score', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('execution_guidance', sa.String(), nullable=False),
    sa.Column('factors_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_stress_intraday_as_of_utc'), 'gold_stress_intraday', ['as_of_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gold_stress_intraday_as_of_utc'), table_name='gold_stress_intraday')
    op.drop_table('gold_stress_intraday')
    op.drop_index(op.f('ix_gold_regime_daily_as_of_utc'), table_name='gold_regime_daily')
    op.drop_table('gold_regime_daily')
    op.drop_index(op.f('ix_gold_positioning_snapshot_as_of_utc'), table_name='gold_positioning_snapshot')
    op.drop_table('gold_positioning_snapshot')
    # ### end Alembic commands ###
