"""add plan to subscriptions

Revision ID: ec08183de78e
Revises: 704369b62501
Create Date: 2026-02-09 11:28:42.623557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec08183de78e'
down_revision: Union[str, Sequence[str], None] = '704369b62501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('usage_reset_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'usage_reset_at')
    op.drop_column('subscriptions', 'plan')
    # ### end Alembic commands ###
