"""fix subscription plan/status

Revision ID: fbd8788d9bee
Revises: c44ccc6fe5f5
Create Date: 2026-02-11 16:29:36.879296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd8788d9bee'
down_revision: Union[str, Sequence[str], None] = 'c44ccc6fe5f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
